-- DOJUKU SHINGI — Seed Data
-- Supabase: cbmasgbbhmunzjoqbpcs

-- ========== JAPAN (20 techniques) ==========
INSERT INTO techniques (culture, discipline, name_original, name_romanized, name_english, difficulty, type, position_description) VALUES
('japan', 'karate', '空手', 'karate', 'empty hand', 3, 'kata', 'The way of the empty hand'),
('japan', 'karate', '手刀', 'shuto', 'knife hand', 2, 'strike', 'Open hand strike using the edge'),
('japan', 'judo', '柔道', 'judo', 'gentle way', 3, 'kata', 'The way of flexibility'),
('japan', 'aikido', '合気道', 'aikido', 'way of harmony', 4, 'kata', 'Harmonizing with opponent energy'),
('japan', 'kendo', '剣道', 'kendo', 'way of the sword', 4, 'kata', 'The way of the sword'),
('japan', 'general', '武道', 'budo', 'martial way', 3, 'kata', 'The martial path'),
('japan', 'general', '道場', 'dojo', 'place of the way', 2, 'stance', 'Training hall'),
('japan', 'karate', '型', 'kata', 'form', 3, 'kata', 'Predetermined fighting sequence'),
('japan', 'general', '技', 'waza', 'technique', 2, 'strike', 'Martial arts technique'),
('japan', 'general', '気', 'ki', 'spirit energy', 5, 'stance', 'Internal life force'),
('japan', 'general', '力', 'chikara', 'power', 2, 'strike', 'Physical strength'),
('japan', 'karate', '拳', 'ken', 'fist', 1, 'strike', 'Clenched fist'),
('japan', 'karate', '蹴', 'keri', 'kick', 2, 'strike', 'Foot or leg strike'),
('japan', 'judo', '受', 'uke', 'receive/block', 2, 'block', 'Receiving or blocking'),
('japan', 'judo', '投', 'nage', 'throw', 3, 'throw', 'Throwing technique'),
('japan', 'judo', '極', 'kime', 'focus/decision', 4, 'stance', 'Point of focus and decision'),
('japan', 'karate', '打', 'uchi', 'strike', 1, 'strike', 'Striking technique'),
('japan', 'karate', '突', 'tsuki', 'thrust/punch', 2, 'strike', 'Punching technique'),
('japan', 'karate', '防', 'bo', 'defense', 2, 'block', 'Defensive technique'),
('japan', 'general', '心', 'kokoro', 'heart/mind', 5, 'stance', 'Heart and spirit of the warrior');

-- ========== CHINA (20 techniques) ==========
INSERT INTO techniques (culture, discipline, name_original, name_romanized, name_english, difficulty, type, position_description) VALUES
('china', 'wushu', '武术', 'wushu', 'martial art', 3, 'kata', 'Chinese martial arts'),
('china', 'taichi', '太极', 'taiji', 'supreme ultimate', 4, 'kata', 'Supreme ultimate fist'),
('china', 'kungfu', '功夫', 'gongfu', 'skill/effort', 3, 'kata', 'Mastery through effort'),
('china', 'qigong', '气功', 'qigong', 'breath work', 4, 'stance', 'Cultivation of life energy'),
('china', 'wushu', '拳', 'quan', 'fist', 1, 'strike', 'Fist technique'),
('china', 'wushu', '掌', 'zhang', 'palm', 2, 'strike', 'Open palm strike'),
('china', 'wushu', '腿', 'tui', 'leg', 2, 'strike', 'Leg technique'),
('china', 'wushu', '踢', 'ti', 'kick', 2, 'strike', 'Kicking technique'),
('china', 'wushu', '挡', 'dang', 'block', 2, 'block', 'Blocking technique'),
('china', 'taichi', '推', 'tui', 'push', 2, 'strike', 'Pushing technique'),
('china', 'taichi', '拉', 'la', 'pull', 2, 'throw', 'Pulling technique'),
('china', 'wushu', '劈', 'pi', 'chop', 3, 'strike', 'Chopping downward strike'),
('china', 'wushu', '刺', 'ci', 'pierce', 3, 'strike', 'Piercing technique'),
('china', 'wushu', '勾', 'gou', 'hook', 3, 'strike', 'Hook technique'),
('china', 'wushu', '扫', 'sao', 'sweep', 3, 'throw', 'Sweeping technique'),
('china', 'wushu', '弹', 'tan', 'flick', 2, 'strike', 'Flicking technique'),
('china', 'wushu', '架', 'jia', 'frame/block', 2, 'block', 'Framing defense'),
('china', 'wushu', '闪', 'shan', 'dodge', 3, 'block', 'Evasion technique'),
('china', 'wushu', '步', 'bu', 'step', 1, 'stance', 'Footwork and stepping'),
('china', 'wushu', '桩', 'zhuang', 'stake/post', 4, 'stance', 'Standing meditation posture');

-- ========== KOREA (20 techniques) ==========
INSERT INTO techniques (culture, discipline, name_original, name_romanized, name_english, difficulty, type, position_description) VALUES
('korea', 'taekwondo', '태권도', 'taekwondo', 'way of fist and foot', 3, 'kata', 'Korean martial art of kicking and punching'),
('korea', 'hapkido', '합기도', 'hapkido', 'way of coordinated power', 4, 'kata', 'Korean art of joint locks and throws'),
('korea', 'kumdo', '검도', 'kumdo', 'way of the sword', 4, 'kata', 'Korean sword art'),
('korea', 'taekwondo', '차기', 'chagi', 'kick', 2, 'strike', 'Kicking technique'),
('korea', 'taekwondo', '막기', 'makgi', 'block', 2, 'block', 'Blocking technique'),
('korea', 'taekwondo', '지르기', 'jireugi', 'punch', 2, 'strike', 'Punching technique'),
('korea', 'taekwondo', '품새', 'poomsae', 'form', 3, 'kata', 'Predetermined pattern of techniques'),
('korea', 'taekwondo', '겨루기', 'gyeorugi', 'sparring', 3, 'kata', 'Free sparring'),
('korea', 'taekwondo', '격파', 'gyeokpa', 'breaking', 4, 'strike', 'Board or brick breaking'),
('korea', 'taekwondo', '단', 'dan', 'rank/degree', 1, 'stance', 'Black belt degree'),
('korea', 'taekwondo', '관', 'gwan', 'school', 1, 'stance', 'Martial arts school'),
('korea', 'general', '도장', 'dojang', 'training hall', 1, 'stance', 'Korean martial arts training hall'),
('korea', 'taekwondo', '띠', 'tti', 'belt', 1, 'stance', 'Martial arts belt'),
('korea', 'taekwondo', '발차기', 'balchagi', 'foot kick', 2, 'strike', 'Foot kicking technique'),
('korea', 'taekwondo', '손기술', 'songisul', 'hand technique', 2, 'strike', 'Hand striking technique'),
('korea', 'taekwondo', '무릎', 'mureup', 'knee', 3, 'strike', 'Knee strike'),
('korea', 'taekwondo', '팔꿈치', 'palkkumchi', 'elbow', 3, 'strike', 'Elbow strike'),
('korea', 'taekwondo', '머리', 'meori', 'head', 2, 'block', 'Head area target'),
('korea', 'taekwondo', '몸', 'mom', 'body', 1, 'block', 'Body area target'),
('korea', 'taekwondo', '기합', 'kihap', 'spirit shout', 2, 'stance', 'Martial spirit yell');

-- ========== VIETNAM (20 techniques) ==========
INSERT INTO techniques (culture, discipline, name_original, name_romanized, name_english, difficulty, type, position_description) VALUES
('vietnam', 'vovinam', 'Việt Võ Đạo', 'viet vo dao', 'Vietnamese martial way', 4, 'kata', 'The way of Vietnamese martial arts'),
('vietnam', 'vovinam', 'Vovinam', 'vovinam', 'Vietnamese martial arts', 3, 'kata', 'Vietnamese martial art system'),
('vietnam', 'vovinam', 'đấm', 'dam', 'punch', 1, 'strike', 'Punching technique'),
('vietnam', 'vovinam', 'đá', 'da', 'kick', 2, 'strike', 'Kicking technique'),
('vietnam', 'vovinam', 'chặt', 'chat', 'chop', 2, 'strike', 'Chopping strike'),
('vietnam', 'vovinam', 'gạt', 'gat', 'deflect', 2, 'block', 'Deflection technique'),
('vietnam', 'vovinam', 'đỡ', 'do', 'support/block', 2, 'block', 'Blocking technique'),
('vietnam', 'vovinam', 'né', 'ne', 'dodge', 3, 'block', 'Dodging technique'),
('vietnam', 'vovinam', 'thế', 'the', 'position', 2, 'stance', 'Combat position'),
('vietnam', 'vovinam', 'quyền', 'quyen', 'form/fist', 3, 'kata', 'Form or fist technique'),
('vietnam', 'vovinam', 'chiến lược', 'chien luoc', 'strategy', 4, 'stance', 'Combat strategy'),
('vietnam', 'vovinam', 'song đấu', 'song dau', 'sparring', 3, 'kata', 'Partner sparring'),
('vietnam', 'vovinam', 'tự vệ', 'tu ve', 'self defense', 3, 'block', 'Self-defense technique'),
('vietnam', 'vovinam', 'vật', 'vat', 'wrestle', 3, 'throw', 'Wrestling technique'),
('vietnam', 'vovinam', 'khóa', 'khoa', 'lock', 4, 'throw', 'Joint lock technique'),
('vietnam', 'vovinam', 'đòn', 'don', 'combination', 3, 'strike', 'Combination technique'),
('vietnam', 'vovinam', 'thủ', 'thu', 'defense', 2, 'block', 'Defensive posture'),
('vietnam', 'vovinam', 'công', 'cong', 'attack', 2, 'strike', 'Attack technique'),
('vietnam', 'vovinam', 'bước', 'buoc', 'step', 1, 'stance', 'Stepping footwork'),
('vietnam', 'vovinam', 'thở', 'tho', 'breathe', 5, 'stance', 'Breathing meditation');

-- ========== BRAZIL (20 techniques) ==========
INSERT INTO techniques (culture, discipline, name_original, name_romanized, name_english, difficulty, type, position_description) VALUES
('brazil', 'capoeira', 'Capoeira', 'capoeira', 'capoeira', 3, 'kata', 'Brazilian martial art with dance and music'),
('brazil', 'bjj', 'Jiu-Jitsu', 'jiu-jitsu', 'Brazilian jiu-jitsu', 4, 'kata', 'Ground fighting martial art'),
('brazil', 'capoeira', 'ginga', 'ginga', 'sway', 2, 'stance', 'Basic capoeira movement'),
('brazil', 'capoeira', 'meia-lua', 'meia-lua', 'half moon', 3, 'strike', 'Half-moon kick'),
('brazil', 'capoeira', 'armada', 'armada', 'spinning kick', 3, 'strike', 'Spinning outside kick'),
('brazil', 'capoeira', 'queixada', 'queixada', 'jaw strike', 3, 'strike', 'Outside crescent kick'),
('brazil', 'capoeira', 'au', 'au', 'cartwheel', 2, 'stance', 'Cartwheel movement'),
('brazil', 'capoeira', 'macaco', 'macaco', 'monkey flip', 4, 'throw', 'Backward handspring'),
('brazil', 'capoeira', 'rasteira', 'rasteira', 'leg sweep', 3, 'throw', 'Sweeping takedown'),
('brazil', 'capoeira', 'esquiva', 'esquiva', 'dodge', 2, 'block', 'Evasive movement'),
('brazil', 'capoeira', 'role', 'role', 'roll', 2, 'stance', 'Rolling movement'),
('brazil', 'capoeira', 'negativa', 'negativa', 'negative', 3, 'block', 'Low evasive position'),
('brazil', 'bjj', 'ponte', 'ponte', 'bridge', 2, 'throw', 'Bridge escape'),
('brazil', 'bjj', 'guarda', 'guarda', 'guard', 2, 'stance', 'Guard position'),
('brazil', 'bjj', 'montada', 'montada', 'mount', 3, 'stance', 'Mount position'),
('brazil', 'bjj', 'passagem', 'passagem', 'guard pass', 4, 'throw', 'Passing the guard'),
('brazil', 'bjj', 'chave', 'chave', 'key lock', 4, 'throw', 'Joint lock submission'),
('brazil', 'bjj', 'triangulo', 'triangulo', 'triangle', 4, 'throw', 'Triangle choke'),
('brazil', 'bjj', 'raspagem', 'raspagem', 'sweep', 3, 'throw', 'Guard sweep'),
('brazil', 'bjj', 'finalizacao', 'finalizacao', 'submission', 5, 'throw', 'Submission technique');

-- ========== QUIZ QUESTIONS (50+) ==========
INSERT INTO quiz_questions (statement_en, is_true, category, culture) VALUES
('Karate originated in Okinawa, Japan.', true, 'history', 'japan'),
('Judo was created by Jigoro Kano in 1882.', true, 'history', 'japan'),
('A black belt means you have mastered the art.', false, 'general', NULL),
('Taekwondo is the national sport of South Korea.', true, 'history', 'korea'),
('Capoeira was developed by enslaved Africans in Brazil.', true, 'history', 'brazil'),
('Kung Fu is a single martial art style.', false, 'general', 'china'),
('Tai Chi was originally developed as a martial art.', true, 'history', 'china'),
('The word "Dojo" means "place of the way".', true, 'language', 'japan'),
('Brazilian Jiu-Jitsu focuses primarily on striking.', false, 'general', 'brazil'),
('Vovinam was founded in 1938 in Hanoi, Vietnam.', true, 'history', 'vietnam'),
('Aikido emphasizes redirecting an attacker''s energy.', true, 'technique', 'japan'),
('A white belt is the highest rank in martial arts.', false, 'general', NULL),
('Hapkido combines striking, kicking, and joint locks.', true, 'technique', 'korea'),
('The ginga is the fundamental movement in Capoeira.', true, 'technique', 'brazil'),
('Wushu is the Chinese term for martial arts.', true, 'language', 'china'),
('Taekwondo means "the way of the hand and foot".', true, 'language', 'korea'),
('Kendo practitioners use real swords for training.', false, 'general', 'japan'),
('Qigong focuses on cultivating life energy through breath.', true, 'technique', 'china'),
('BJJ was adapted from Judo by the Gracie family.', true, 'history', 'brazil'),
('The Vietnam martial art Vovinam uses only hand techniques.', false, 'general', 'vietnam'),
('Karate means "empty hand" in Japanese.', true, 'language', 'japan'),
('A poomsae is a Korean martial arts form.', true, 'technique', 'korea'),
('Martial arts training always requires a weapon.', false, 'general', NULL),
('The term "Ki" refers to internal energy in Japanese martial arts.', true, 'language', 'japan'),
('Tai Chi is typically practiced very quickly.', false, 'general', 'china'),
('Capoeira incorporates music and singing into practice.', true, 'culture', 'brazil'),
('All martial arts originated in East Asia.', false, 'general', NULL),
('Judo means "the gentle way" in Japanese.', true, 'language', 'japan'),
('Gyeokpa (breaking) is a discipline in Taekwondo.', true, 'technique', 'korea'),
('Vovinam emphasizes the balance of hard and soft techniques.', true, 'technique', 'vietnam'),
('The berimbau is an instrument used in Capoeira.', true, 'culture', 'brazil'),
('Kung Fu can take decades to truly master.', true, 'general', 'china'),
('Sumo is a form of Taekwondo.', false, 'general', 'japan'),
('Hapkido was influenced by Japanese Aikido.', true, 'history', 'korea'),
('The Vietnamese martial art community values respect for elders.', true, 'culture', 'vietnam'),
('A "Mestre" in Capoeira is equivalent to a black belt.', true, 'general', 'brazil'),
('Judo was the first martial art included in the Olympics.', true, 'history', 'japan'),
('Wushu competitions include both forms and sparring.', true, 'technique', 'china'),
('Taekwondo was added to the Olympics in 2000 in Sydney.', true, 'history', 'korea'),
('Vovinam uses a blue uniform called "vo phuc".', true, 'culture', 'vietnam'),
('Capoeira was once banned in Brazil.', true, 'history', 'brazil'),
('The concept of "Do" (way/path) is unique to Japanese arts.', false, 'general', NULL),
('Shaolin monks are associated with Kung Fu development.', true, 'history', 'china'),
('A "Kihap" is a spirit shout used in Korean martial arts.', true, 'language', 'korea'),
('Vietnamese martial arts have no influence from Chinese styles.', false, 'general', 'vietnam'),
('The "roda" is the circle where Capoeira is played.', true, 'culture', 'brazil'),
('Aikido was founded by Morihei Ueshiba.', true, 'history', 'japan'),
('Wing Chun is a style of Kung Fu.', true, 'technique', 'china'),
('Breaking boards requires no technique, only strength.', false, 'general', NULL),
('Meditation is an important part of many martial arts.', true, 'general', NULL),
('The belt system was invented in the 20th century.', true, 'history', NULL),
('Martial arts training can improve mental discipline.', true, 'general', NULL);

-- ========== ACHIEVEMENT DEFINITIONS ==========
INSERT INTO achievement_definitions (key, name, description, icon, requirement_type, requirement_value, honor_reward) VALUES
('first_game', 'First Step', 'Complete your first game', '🥋', 'games_played', 1, 50),
('ten_games', 'Dedicated Student', 'Complete 10 games', '🔥', 'games_played', 10, 100),
('fifty_games', 'Warrior Spirit', 'Complete 50 games', '⚔️', 'games_played', 50, 250),
('hundred_games', 'Grand Master', 'Complete 100 games', '🏆', 'games_played', 100, 500),
('belt_yellow', 'Yellow Belt', 'Reach Yellow belt', '🟡', 'belt_level', 1, 100),
('belt_orange', 'Orange Belt', 'Reach Orange belt', '🟠', 'belt_level', 2, 150),
('belt_green', 'Green Belt', 'Reach Green belt', '🟢', 'belt_level', 3, 200),
('belt_blue', 'Blue Belt', 'Reach Blue belt', '🔵', 'belt_level', 4, 300),
('belt_brown', 'Brown Belt', 'Reach Brown belt', '🟤', 'belt_level', 5, 400),
('belt_black', 'Black Belt', 'Reach Black belt', '⬛', 'belt_level', 6, 1000),
('perfect_3stars', 'Perfection', 'Get 3 stars on any game', '⭐', 'max_stars', 3, 75),
('five_cultures', 'World Traveler', 'Play games from all 5 cultures', '🌍', 'cultures_played', 5, 200),
('combo_5', 'Combo Master', 'Reach a 5x combo', '💥', 'max_combo', 5, 100),
('combo_10', 'Unstoppable', 'Reach a 10x combo', '🌪️', 'max_combo', 10, 250),
('writing_master', 'Calligraphy Master', 'Complete all 6 writing games', '✍️', 'writing_games', 6, 200),
('stance_master', 'Position Master', 'Complete all 6 position games', '🧘', 'stance_games', 6, 200),
('culture_master', 'Culture Master', 'Complete all 6 culture games', '🎌', 'culture_games', 6, 200),
('all_games', 'Complete Collection', 'Play all 18 games at least once', '👑', 'unique_games', 18, 500);
